# Generated by Django 4.2.7 on 2023-11-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_padaria_aa', '0002_produto_remove_encomenda_data_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
