# Generated by Django 4.2.7 on 2023-11-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padaria_aa', '0003_remove_encomenda_produto_remove_pedido_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
